import { ATSProfile, KeywordRegistry } from "../types/config";
import { deriveSkillAliases } from "../utils/skills";

// ponytail: broad seed set per category, still not an exhaustive taxonomy — grow on demand.
export const defaultKeywordRegistry: KeywordRegistry = [
  // languages / frameworks
  // ponytail: "node" split from javascript — Node.js runtime !== JS language
  { canonical: "javascript", aliases: ["js", "ecmascript", "es6"], category: "technical" },
  { canonical: "node", aliases: ["node.js", "nodejs"], category: "technical" },
  { canonical: "typescript", aliases: ["ts"], category: "technical" },
  { canonical: "react", aliases: ["reactjs", "react.js"], category: "technical" },
  { canonical: "angular", aliases: ["angularjs", "angular2+"], category: "technical" },
  { canonical: "vue", aliases: ["vue.js", "vuejs"], category: "technical" },
  { canonical: "svelte", aliases: ["sveltekit"], category: "technical" },
  { canonical: "next.js", aliases: ["nextjs"], category: "technical" },
  { canonical: "nuxt.js", aliases: ["nuxtjs", "nuxt"], category: "technical" },
  { canonical: "remix", aliases: [], category: "technical" },
  { canonical: "c++", aliases: ["cpp"], category: "technical" },
  { canonical: "c#", aliases: ["csharp", ".net"], category: "technical" },
  { canonical: "java", aliases: [], category: "technical" },
  { canonical: "python", aliases: ["py"], category: "technical" },
  { canonical: "go", aliases: ["golang"], category: "technical" },
  { canonical: "rust", aliases: [], category: "technical" },
  { canonical: "ruby", aliases: ["ruby on rails", "rails"], category: "technical" },
  { canonical: "php", aliases: [], category: "technical" },
  { canonical: "swift", aliases: ["swiftui"], category: "technical" },
  { canonical: "kotlin", aliases: [], category: "technical" },
  { canonical: "scala", aliases: [], category: "technical" },
  { canonical: "perl", aliases: [], category: "technical" },
  { canonical: "r", aliases: ["r language", "r programming"], category: "technical" },
  { canonical: "matlab", aliases: [], category: "technical" },
  { canonical: "objective-c", aliases: ["objective c", "objc"], category: "technical" },
  { canonical: "dart", aliases: [], category: "technical" },
  { canonical: "elixir", aliases: [], category: "technical" },
  { canonical: "haskell", aliases: [], category: "technical" },
  { canonical: "html", aliases: ["html5"], category: "technical" },
  { canonical: "css", aliases: ["css3"], category: "technical" },
  { canonical: "sass", aliases: ["scss"], category: "technical" },
  { canonical: "less", aliases: [], category: "technical" },
  { canonical: "tailwind css", aliases: ["tailwind", "tailwindcss"], category: "technical" },
  { canonical: "bootstrap", aliases: [], category: "technical" },
  { canonical: "webassembly", aliases: ["wasm"], category: "technical" },
  { canonical: "ios development", aliases: ["ios"], category: "technical" },
  { canonical: "android development", aliases: ["android"], category: "technical" },
  { canonical: "react native", aliases: [], category: "technical" },
  { canonical: "flutter", aliases: [], category: "technical" },
  { canonical: "xamarin", aliases: [], category: "technical" },
  { canonical: "machine learning", aliases: ["ml"], category: "technical" },
  { canonical: "deep learning", aliases: ["dl"], category: "technical" },
  { canonical: "natural language processing", aliases: ["nlp"], category: "technical" },
  { canonical: "computer vision", aliases: ["cv"], category: "technical" },
  { canonical: "large language models", aliases: ["llm", "llms"], category: "technical" },
  { canonical: "generative ai", aliases: ["genai", "gen ai"], category: "technical" },
  { canonical: "reinforcement learning", aliases: ["rl"], category: "technical" },
  { canonical: "neural networks", aliases: ["neural network"], category: "technical" },
  { canonical: "data engineering", aliases: [], category: "technical" },
  { canonical: "data warehousing", aliases: ["data warehouse"], category: "technical" },
  { canonical: "etl", aliases: ["extract transform load", "elt"], category: "technical" },
  { canonical: "distributed systems", aliases: [], category: "technical" },
  { canonical: "embedded systems", aliases: [], category: "technical" },
  { canonical: "firmware development", aliases: ["firmware"], category: "technical" },
  { canonical: "game development", aliases: [], category: "technical" },
  { canonical: "unity", aliases: [], category: "technical" },
  { canonical: "unreal engine", aliases: ["unreal"], category: "technical" },
  { canonical: "web development", aliases: [], category: "technical" },
  { canonical: "full stack development", aliases: ["full-stack development", "full stack"], category: "technical" },
  { canonical: "api development", aliases: [], category: "technical" },
  { canonical: "grpc", aliases: [], category: "technical" },
  { canonical: "websockets", aliases: ["websocket"], category: "technical" },
  { canonical: "linux", aliases: [], category: "technical" },
  { canonical: "unix", aliases: [], category: "technical" },
  { canonical: "bash scripting", aliases: ["bash", "shell scripting"], category: "technical" },
  { canonical: "powershell", aliases: [], category: "technical" },
  // tools / platforms / infra
  { canonical: "sql", aliases: ["structured query language"], category: "tool" },
  { canonical: "postgresql", aliases: ["postgres", "psql"], category: "tool" },
  { canonical: "mysql", aliases: [], category: "tool" },
  { canonical: "sqlite", aliases: [], category: "tool" },
  { canonical: "microsoft sql server", aliases: ["mssql", "sql server", "t-sql"], category: "tool" },
  { canonical: "oracle database", aliases: ["oracle db", "oracle"], category: "tool" },
  { canonical: "mongodb", aliases: ["mongo"], category: "tool" },
  { canonical: "cassandra", aliases: ["apache cassandra"], category: "tool" },
  { canonical: "dynamodb", aliases: ["amazon dynamodb"], category: "tool" },
  { canonical: "couchbase", aliases: [], category: "tool" },
  { canonical: "neo4j", aliases: [], category: "tool" },
  { canonical: "firebase", aliases: [], category: "tool" },
  { canonical: "supabase", aliases: [], category: "tool" },
  { canonical: "graphql", aliases: ["gql"], category: "tool" },
  { canonical: "aws", aliases: ["amazon web services"], category: "tool" },
  { canonical: "amazon ec2", aliases: ["ec2"], category: "tool" },
  { canonical: "amazon s3", aliases: ["s3"], category: "tool" },
  { canonical: "amazon rds", aliases: ["rds"], category: "tool" },
  { canonical: "aws lambda", aliases: ["lambda"], category: "tool" },
  { canonical: "amazon cloudfront", aliases: ["cloudfront"], category: "tool" },
  { canonical: "amazon sqs", aliases: ["sqs"], category: "tool" },
  { canonical: "amazon sns", aliases: ["sns"], category: "tool" },
  { canonical: "azure", aliases: ["microsoft azure"], category: "tool" },
  { canonical: "azure devops", aliases: [], category: "tool" },
  { canonical: "azure functions", aliases: [], category: "tool" },
  { canonical: "google cloud platform", aliases: ["gcp", "google cloud"], category: "tool" },
  { canonical: "google bigquery", aliases: ["bigquery"], category: "tool" },
  { canonical: "google kubernetes engine", aliases: ["gke"], category: "tool" },
  { canonical: "docker", aliases: ["containers", "containerization"], category: "tool" },
  { canonical: "kubernetes", aliases: ["k8s"], category: "tool" },
  { canonical: "helm", aliases: [], category: "tool" },
  { canonical: "terraform", aliases: [], category: "tool" },
  { canonical: "pulumi", aliases: [], category: "tool" },
  { canonical: "ansible", aliases: [], category: "tool" },
  { canonical: "puppet", aliases: [], category: "tool" },
  { canonical: "chef", aliases: [], category: "tool" },
  { canonical: "jenkins", aliases: [], category: "tool" },
  { canonical: "circleci", aliases: ["circle ci"], category: "tool" },
  { canonical: "github actions", aliases: [], category: "tool" },
  { canonical: "gitlab ci", aliases: ["gitlab ci/cd"], category: "tool" },
  { canonical: "travis ci", aliases: [], category: "tool" },
  { canonical: "git", aliases: ["github", "gitlab", "bitbucket"], category: "tool" },
  { canonical: "jira", aliases: [], category: "tool" },
  { canonical: "confluence", aliases: [], category: "tool" },
  { canonical: "trello", aliases: [], category: "tool" },
  { canonical: "asana", aliases: [], category: "tool" },
  { canonical: "monday.com", aliases: ["monday"], category: "tool" },
  { canonical: "notion", aliases: [], category: "tool" },
  { canonical: "linear", aliases: [], category: "tool" },
  { canonical: "slack", aliases: [], category: "tool" },
  { canonical: "microsoft teams", aliases: ["ms teams"], category: "tool" },
  { canonical: "pytorch", aliases: ["torch"], category: "tool" },
  { canonical: "tensorflow", aliases: ["tf"], category: "tool" },
  { canonical: "keras", aliases: [], category: "tool" },
  { canonical: "scikit-learn", aliases: ["sklearn"], category: "tool" },
  { canonical: "pandas", aliases: [], category: "tool" },
  { canonical: "numpy", aliases: [], category: "tool" },
  { canonical: "hugging face", aliases: ["huggingface", "transformers"], category: "tool" },
  { canonical: "langchain", aliases: [], category: "tool" },
  { canonical: "openai api", aliases: ["openai", "gpt api"], category: "tool" },
  { canonical: "jupyter", aliases: ["jupyter notebook"], category: "tool" },
  { canonical: "fastapi", aliases: [], category: "tool" },
  { canonical: "flask", aliases: [], category: "tool" },
  { canonical: "django", aliases: [], category: "tool" },
  { canonical: "express.js", aliases: ["express", "expressjs"], category: "tool" },
  { canonical: "spring boot", aliases: ["spring"], category: "tool" },
  { canonical: "laravel", aliases: [], category: "tool" },
  { canonical: "kafka", aliases: ["apache kafka"], category: "tool" },
  { canonical: "rabbitmq", aliases: [], category: "tool" },
  { canonical: "redis", aliases: [], category: "tool" },
  { canonical: "memcached", aliases: [], category: "tool" },
  { canonical: "elasticsearch", aliases: ["elastic"], category: "tool" },
  { canonical: "logstash", aliases: [], category: "tool" },
  { canonical: "kibana", aliases: [], category: "tool" },
  { canonical: "grafana", aliases: [], category: "tool" },
  { canonical: "prometheus", aliases: [], category: "tool" },
  { canonical: "datadog", aliases: [], category: "tool" },
  { canonical: "new relic", aliases: [], category: "tool" },
  { canonical: "splunk", aliases: [], category: "tool" },
  { canonical: "spark", aliases: ["apache spark", "pyspark"], category: "tool" },
  { canonical: "hadoop", aliases: ["apache hadoop"], category: "tool" },
  { canonical: "airflow", aliases: ["apache airflow"], category: "tool" },
  { canonical: "dbt", aliases: ["data build tool"], category: "tool" },
  { canonical: "snowflake", aliases: [], category: "tool" },
  { canonical: "databricks", aliases: [], category: "tool" },
  { canonical: "looker", aliases: [], category: "tool" },
  { canonical: "tableau", aliases: [], category: "tool" },
  { canonical: "power bi", aliases: ["powerbi"], category: "tool" },
  { canonical: "excel", aliases: ["microsoft excel", "ms excel"], category: "tool" },
  { canonical: "google sheets", aliases: [], category: "tool" },
  { canonical: "spss", aliases: [], category: "tool" },
  { canonical: "sas", aliases: [], category: "tool" },
  { canonical: "salesforce", aliases: [], category: "tool" },
  { canonical: "hubspot", aliases: [], category: "tool" },
  { canonical: "marketo", aliases: [], category: "tool" },
  { canonical: "mailchimp", aliases: [], category: "tool" },
  { canonical: "google analytics", aliases: ["ga4"], category: "tool" },
  { canonical: "google tag manager", aliases: ["gtm"], category: "tool" },
  { canonical: "sap", aliases: [], category: "tool" },
  { canonical: "quickbooks", aliases: [], category: "tool" },
  { canonical: "netsuite", aliases: [], category: "tool" },
  { canonical: "workday", aliases: [], category: "tool" },
  { canonical: "zendesk", aliases: [], category: "tool" },
  { canonical: "servicenow", aliases: [], category: "tool" },
  { canonical: "freshdesk", aliases: [], category: "tool" },
  { canonical: "figma", aliases: [], category: "tool" },
  { canonical: "sketch", aliases: [], category: "tool" },
  { canonical: "adobe xd", aliases: ["xd"], category: "tool" },
  { canonical: "invision", aliases: [], category: "tool" },
  { canonical: "photoshop", aliases: ["adobe photoshop"], category: "tool" },
  { canonical: "illustrator", aliases: ["adobe illustrator"], category: "tool" },
  { canonical: "after effects", aliases: ["adobe after effects"], category: "tool" },
  { canonical: "premiere pro", aliases: ["adobe premiere"], category: "tool" },
  { canonical: "autocad", aliases: [], category: "tool" },
  { canonical: "solidworks", aliases: [], category: "tool" },
  { canonical: "postman", aliases: [], category: "tool" },
  { canonical: "selenium", aliases: [], category: "tool" },
  { canonical: "cypress", aliases: [], category: "tool" },
  { canonical: "playwright", aliases: [], category: "tool" },
  { canonical: "jest", aliases: [], category: "tool" },
  { canonical: "mocha", aliases: [], category: "tool" },
  { canonical: "junit", aliases: [], category: "tool" },
  // engineering concepts
  { canonical: "accessibility", aliases: ["a11y"], category: "concept" },
  { canonical: "frontend", aliases: ["front-end"], category: "concept" },
  { canonical: "backend", aliases: ["back-end"], category: "concept" },
  { canonical: "security", aliases: ["cybersecurity", "infosec"], category: "concept" },
  { canonical: "application security", aliases: ["appsec"], category: "concept" },
  { canonical: "penetration testing", aliases: ["pentesting", "pen testing"], category: "concept" },
  { canonical: "vulnerability assessment", aliases: [], category: "concept" },
  { canonical: "identity and access management", aliases: ["iam"], category: "concept" },
  { canonical: "zero trust", aliases: [], category: "concept" },
  { canonical: "encryption", aliases: [], category: "concept" },
  { canonical: "testing", aliases: ["unittest", "pytest"], category: "concept" },
  { canonical: "unit testing", aliases: [], category: "concept" },
  { canonical: "integration testing", aliases: [], category: "concept" },
  { canonical: "end-to-end testing", aliases: ["e2e testing"], category: "concept" },
  { canonical: "regression testing", aliases: [], category: "concept" },
  { canonical: "microservices", aliases: [], category: "concept" },
  { canonical: "monolithic architecture", aliases: ["monolith"], category: "concept" },
  { canonical: "event-driven architecture", aliases: ["event driven architecture"], category: "concept" },
  { canonical: "serverless", aliases: ["serverless architecture"], category: "concept" },
  { canonical: "agile", aliases: [], category: "concept" },
  { canonical: "scrum", aliases: [], category: "concept" },
  { canonical: "kanban", aliases: [], category: "concept" },
  { canonical: "waterfall", aliases: [], category: "concept" },
  { canonical: "sprint planning", aliases: [], category: "concept" },
  { canonical: "blockchain", aliases: [], category: "concept" },
  { canonical: "smart contracts", aliases: [], category: "concept" },
  { canonical: "devops", aliases: [], category: "concept" },
  { canonical: "site reliability engineering", aliases: ["sre"], category: "concept" },
  { canonical: "infrastructure as code", aliases: ["iac"], category: "concept" },
  { canonical: "ci/cd", aliases: ["continuous integration", "continuous deployment", "continuous delivery"], category: "concept" },
  { canonical: "rest api", aliases: ["restful api", "rest apis"], category: "concept" },
  { canonical: "api design", aliases: [], category: "concept" },
  { canonical: "design patterns", aliases: [], category: "concept" },
  { canonical: "data structures", aliases: [], category: "concept" },
  { canonical: "algorithms", aliases: [], category: "concept" },
  { canonical: "object-oriented programming", aliases: ["oop", "object oriented programming"], category: "concept" },
  { canonical: "functional programming", aliases: [], category: "concept" },
  { canonical: "cloud computing", aliases: [], category: "concept" },
  { canonical: "cloud migration", aliases: [], category: "concept" },
  { canonical: "system design", aliases: [], category: "concept" },
  { canonical: "high availability", aliases: [], category: "concept" },
  { canonical: "scalability", aliases: [], category: "concept" },
  { canonical: "load balancing", aliases: [], category: "concept" },
  { canonical: "caching", aliases: [], category: "concept" },
  { canonical: "tdd", aliases: ["test driven development", "test-driven development"], category: "concept" },
  { canonical: "bdd", aliases: ["behavior driven development", "behavior-driven development"], category: "concept" },
  { canonical: "code review", aliases: ["code reviews"], category: "concept" },
  { canonical: "pair programming", aliases: [], category: "concept" },
  { canonical: "ux design", aliases: ["user experience"], category: "concept" },
  { canonical: "ui design", aliases: ["user interface design"], category: "concept" },
  { canonical: "user research", aliases: [], category: "concept" },
  { canonical: "wireframing", aliases: [], category: "concept" },
  { canonical: "prototyping", aliases: [], category: "concept" },
  { canonical: "design systems", aliases: [], category: "concept" },
  { canonical: "responsive design", aliases: [], category: "concept" },
  { canonical: "project management", aliases: [], category: "concept" },
  { canonical: "program management", aliases: [], category: "concept" },
  { canonical: "change management", aliases: [], category: "concept" },
  { canonical: "risk management", aliases: [], category: "concept" },
  { canonical: "quality assurance", aliases: ["qa"], category: "concept" },
  { canonical: "data privacy", aliases: [], category: "concept" },
  { canonical: "version control", aliases: [], category: "concept" },
  { canonical: "documentation", aliases: ["technical documentation"], category: "concept" },
  { canonical: "requirements gathering", aliases: [], category: "concept" },
  { canonical: "business process improvement", aliases: [], category: "concept" },
  { canonical: "root cause analysis", aliases: [], category: "concept" },
  { canonical: "lean", aliases: ["lean methodology"], category: "concept" },
  { canonical: "six sigma", aliases: [], category: "concept" },
  // product / data domain
  { canonical: "roadmap", aliases: ["product roadmap"], category: "domain" },
  { canonical: "stakeholder management", aliases: [], category: "domain" },
  { canonical: "prioritization", aliases: [], category: "domain" },
  { canonical: "a/b testing", aliases: ["ab testing"], category: "domain" },
  { canonical: "analytics", aliases: [], category: "domain" },
  { canonical: "statistics", aliases: ["stats"], category: "domain" },
  { canonical: "data visualization", aliases: [], category: "domain" },
  { canonical: "data governance", aliases: [], category: "domain" },
  { canonical: "product management", aliases: [], category: "domain" },
  { canonical: "product strategy", aliases: [], category: "domain" },
  { canonical: "go-to-market strategy", aliases: ["go to market", "gtm strategy"], category: "domain" },
  { canonical: "user story writing", aliases: ["user stories"], category: "domain" },
  { canonical: "competitive analysis", aliases: [], category: "domain" },
  { canonical: "okrs", aliases: ["objectives and key results"], category: "domain" },
  { canonical: "kpis", aliases: ["key performance indicators"], category: "domain" },
  // finance / accounting domain
  { canonical: "financial analysis", aliases: [], category: "domain" },
  { canonical: "financial modeling", aliases: [], category: "domain" },
  { canonical: "budgeting", aliases: [], category: "domain" },
  { canonical: "forecasting", aliases: [], category: "domain" },
  { canonical: "bookkeeping", aliases: [], category: "domain" },
  { canonical: "accounts payable", aliases: ["ap"], category: "domain" },
  { canonical: "accounts receivable", aliases: ["ar"], category: "domain" },
  { canonical: "payroll", aliases: [], category: "domain" },
  { canonical: "auditing", aliases: ["audit"], category: "domain" },
  { canonical: "tax preparation", aliases: [], category: "domain" },
  { canonical: "gaap", aliases: [], category: "domain" },
  { canonical: "ifrs", aliases: [], category: "domain" },
  { canonical: "reconciliation", aliases: ["account reconciliation"], category: "domain" },
  { canonical: "general ledger", aliases: [], category: "domain" },
  { canonical: "cost accounting", aliases: [], category: "domain" },
  { canonical: "mergers and acquisitions", aliases: ["m&a"], category: "domain" },
  { canonical: "investment banking", aliases: [], category: "domain" },
  { canonical: "portfolio management", aliases: [], category: "domain" },
  { canonical: "equity research", aliases: [], category: "domain" },
  { canonical: "treasury management", aliases: ["treasury"], category: "domain" },
  { canonical: "fintech", aliases: [], category: "domain" },
  { canonical: "payments processing", aliases: ["payment processing"], category: "domain" },
  // sales / account management domain
  { canonical: "lead generation", aliases: [], category: "domain" },
  { canonical: "account management", aliases: [], category: "domain" },
  { canonical: "crm", aliases: ["customer relationship management"], category: "domain" },
  { canonical: "sales pipeline", aliases: ["pipeline management"], category: "domain" },
  { canonical: "cold calling", aliases: [], category: "domain" },
  { canonical: "upselling", aliases: ["cross-selling"], category: "domain" },
  { canonical: "customer retention", aliases: [], category: "domain" },
  { canonical: "business development", aliases: ["bizdev"], category: "domain" },
  { canonical: "quota attainment", aliases: [], category: "domain" },
  { canonical: "b2b sales", aliases: [], category: "domain" },
  { canonical: "b2c sales", aliases: [], category: "domain" },
  { canonical: "saas", aliases: ["software as a service"], category: "domain" },
  { canonical: "e-commerce", aliases: ["ecommerce"], category: "domain" },
  // human resources domain
  { canonical: "recruiting", aliases: ["talent acquisition"], category: "domain" },
  { canonical: "onboarding", aliases: [], category: "domain" },
  { canonical: "employee relations", aliases: [], category: "domain" },
  { canonical: "benefits administration", aliases: [], category: "domain" },
  { canonical: "performance management", aliases: [], category: "domain" },
  { canonical: "compensation and benefits", aliases: ["comp and benefits"], category: "domain" },
  { canonical: "diversity and inclusion", aliases: ["dei"], category: "domain" },
  { canonical: "employee engagement", aliases: [], category: "domain" },
  { canonical: "hris", aliases: ["human resources information system"], category: "domain" },
  // healthcare domain
  { canonical: "patient care", aliases: [], category: "domain" },
  { canonical: "clinical documentation", aliases: [], category: "domain" },
  { canonical: "hipaa", aliases: [], category: "domain" },
  { canonical: "electronic health records", aliases: ["ehr", "emr"], category: "domain" },
  { canonical: "medical billing", aliases: [], category: "domain" },
  { canonical: "medical coding", aliases: ["icd-10", "cpt coding"], category: "domain" },
  { canonical: "telehealth", aliases: [], category: "domain" },
  { canonical: "clinical trials", aliases: [], category: "domain" },
  { canonical: "regulatory affairs", aliases: [], category: "domain" },
  // legal domain
  { canonical: "contract review", aliases: [], category: "domain" },
  { canonical: "legal research", aliases: [], category: "domain" },
  { canonical: "litigation", aliases: [], category: "domain" },
  { canonical: "regulatory compliance", aliases: ["compliance"], category: "domain" },
  { canonical: "due diligence", aliases: [], category: "domain" },
  { canonical: "intellectual property", aliases: ["ip law"], category: "domain" },
  { canonical: "gdpr", aliases: ["general data protection regulation"], category: "domain" },
  { canonical: "soc 2", aliases: ["soc2"], category: "domain" },
  { canonical: "iso 27001", aliases: [], category: "domain" },
  { canonical: "pci dss", aliases: ["pci compliance"], category: "domain" },
  // education domain
  { canonical: "curriculum development", aliases: [], category: "domain" },
  { canonical: "lesson planning", aliases: [], category: "domain" },
  { canonical: "classroom management", aliases: [], category: "domain" },
  { canonical: "instructional design", aliases: [], category: "domain" },
  { canonical: "student assessment", aliases: [], category: "domain" },
  { canonical: "e-learning", aliases: ["elearning"], category: "domain" },
  // operations / supply chain domain
  { canonical: "supply chain management", aliases: ["supply chain"], category: "domain" },
  { canonical: "inventory management", aliases: [], category: "domain" },
  { canonical: "procurement", aliases: [], category: "domain" },
  { canonical: "vendor management", aliases: [], category: "domain" },
  { canonical: "logistics", aliases: [], category: "domain" },
  { canonical: "warehouse management", aliases: [], category: "domain" },
  { canonical: "demand planning", aliases: [], category: "domain" },
  { canonical: "manufacturing", aliases: [], category: "domain" },
  { canonical: "quality control", aliases: [], category: "domain" },
  { canonical: "lean manufacturing", aliases: [], category: "domain" },
  // customer service domain
  { canonical: "customer support", aliases: ["customer service"], category: "domain" },
  { canonical: "technical support", aliases: [], category: "domain" },
  { canonical: "conflict resolution", aliases: [], category: "domain" },
  { canonical: "customer success", aliases: [], category: "domain" },
  { canonical: "help desk", aliases: ["helpdesk"], category: "domain" },
  // soft skills
  { canonical: "communication", aliases: [], category: "soft" },
  { canonical: "written communication", aliases: [], category: "soft" },
  { canonical: "verbal communication", aliases: [], category: "soft" },
  { canonical: "leadership", aliases: [], category: "soft" },
  { canonical: "team leadership", aliases: [], category: "soft" },
  { canonical: "teamwork", aliases: ["collaboration"], category: "soft" },
  { canonical: "cross-functional collaboration", aliases: ["cross functional collaboration"], category: "soft" },
  { canonical: "problem solving", aliases: ["problem-solving"], category: "soft" },
  { canonical: "adaptability", aliases: ["flexibility"], category: "soft" },
  { canonical: "time management", aliases: [], category: "soft" },
  { canonical: "critical thinking", aliases: [], category: "soft" },
  { canonical: "creativity", aliases: [], category: "soft" },
  { canonical: "attention to detail", aliases: [], category: "soft" },
  { canonical: "decision making", aliases: ["decision-making"], category: "soft" },
  { canonical: "emotional intelligence", aliases: [], category: "soft" },
  { canonical: "negotiation", aliases: [], category: "soft" },
  { canonical: "organization", aliases: ["organizational skills"], category: "soft" },
  { canonical: "public speaking", aliases: ["presentation skills"], category: "soft" },
  { canonical: "mentoring", aliases: ["coaching"], category: "soft" },
  { canonical: "interpersonal skills", aliases: [], category: "soft" },
  { canonical: "work ethic", aliases: [], category: "soft" },
  { canonical: "stakeholder communication", aliases: [], category: "soft" },
  { canonical: "self-motivation", aliases: ["self motivation"], category: "soft" },
  { canonical: "resilience", aliases: [], category: "soft" },
  { canonical: "empathy", aliases: [], category: "soft" },
  { canonical: "active listening", aliases: [], category: "soft" },
  { canonical: "delegation", aliases: [], category: "soft" },
  { canonical: "strategic thinking", aliases: [], category: "soft" },
  { canonical: "multitasking", aliases: [], category: "soft" },
  // marketing
  { canonical: "seo", aliases: ["search engine optimization"], category: "marketing" },
  { canonical: "sem", aliases: ["search engine marketing"], category: "marketing" },
  { canonical: "branding", aliases: ["brand strategy"], category: "marketing" },
  { canonical: "campaign management", aliases: [], category: "marketing" },
  { canonical: "content marketing", aliases: [], category: "marketing" },
  { canonical: "content strategy", aliases: [], category: "marketing" },
  { canonical: "social media marketing", aliases: ["social media"], category: "marketing" },
  { canonical: "email marketing", aliases: [], category: "marketing" },
  { canonical: "digital marketing", aliases: [], category: "marketing" },
  { canonical: "growth marketing", aliases: ["growth hacking"], category: "marketing" },
  { canonical: "copywriting", aliases: [], category: "marketing" },
  { canonical: "market research", aliases: [], category: "marketing" },
  { canonical: "ppc", aliases: ["pay-per-click", "google ads"], category: "marketing" },
  { canonical: "conversion rate optimization", aliases: ["cro"], category: "marketing" },
  { canonical: "public relations", aliases: ["pr"], category: "marketing" },
  { canonical: "marketing automation", aliases: [], category: "marketing" },
  { canonical: "affiliate marketing", aliases: [], category: "marketing" },
  { canonical: "influencer marketing", aliases: [], category: "marketing" },
  { canonical: "product marketing", aliases: [], category: "marketing" },
  { canonical: "event marketing", aliases: [], category: "marketing" },
  { canonical: "brand awareness", aliases: [], category: "marketing" },
  { canonical: "media planning", aliases: [], category: "marketing" },
  { canonical: "lead nurturing", aliases: [], category: "marketing" },
];

export const defaultSkillAliases = deriveSkillAliases(defaultKeywordRegistry);

export const softwareEngineerProfile: ATSProfile = {
  name: "software-engineer",
  mandatorySkills: ["javascript", "typescript", "react", "node"],
  optionalSkills: ["graphql", "sql", "docker"],
  minExperience: 3,
};

export const dataScientistProfile: ATSProfile = {
  name: "data-scientist",
  mandatorySkills: ["python", "sql", "statistics"],
  optionalSkills: ["pandas", "numpy", "pytorch", "tensorflow"],
  minExperience: 2,
};

export const productManagerProfile: ATSProfile = {
  name: "product-manager",
  mandatorySkills: ["roadmap", "stakeholder management", "prioritization"],
  optionalSkills: ["a/b testing", "analytics", "sql"],
  minExperience: 3,
};

export const defaultProfiles: ATSProfile[] = [
  softwareEngineerProfile,
  dataScientistProfile,
  productManagerProfile,
];
