import { ATSProfile, KeywordRegistry } from "../types/config";
import { deriveSkillAliases } from "../utils/skills";

// ponytail: broad seed set per category, still not an exhaustive taxonomy — grow on demand.
export const defaultKeywordRegistry: KeywordRegistry = [
  // languages / frameworks
  // ponytail: "node" split from javascript — Node.js runtime !== JS language
  { canonical: "javascript", aliases: ["js"], category: "technical" },
  { canonical: "node", aliases: ["node.js", "nodejs"], category: "technical" },
  { canonical: "typescript", aliases: ["ts"], category: "technical" },
  {
    canonical: "react",
    aliases: ["reactjs", "react.js"],
    category: "technical",
  },
  { canonical: "angular", aliases: ["angularjs"], category: "technical" },
  { canonical: "vue", aliases: ["vue.js", "vuejs"], category: "technical" },
  { canonical: "svelte", aliases: [], category: "technical" },
  { canonical: "next.js", aliases: ["nextjs"], category: "technical" },
  { canonical: "c++", aliases: ["cpp"], category: "technical" },
  { canonical: "c#", aliases: ["csharp", ".net"], category: "technical" },
  { canonical: "java", aliases: [], category: "technical" },
  { canonical: "python", aliases: ["py"], category: "technical" },
  { canonical: "go", aliases: ["golang"], category: "technical" },
  { canonical: "rust", aliases: [], category: "technical" },
  {
    canonical: "ruby",
    aliases: ["ruby on rails", "rails"],
    category: "technical",
  },
  { canonical: "php", aliases: [], category: "technical" },
  { canonical: "swift", aliases: [], category: "technical" },
  { canonical: "kotlin", aliases: [], category: "technical" },
  { canonical: "scala", aliases: [], category: "technical" },
  { canonical: "html", aliases: ["html5"], category: "technical" },
  { canonical: "css", aliases: ["css3"], category: "technical" },
  { canonical: "ios development", aliases: ["ios"], category: "technical" },
  {
    canonical: "android development",
    aliases: ["android"],
    category: "technical",
  },
  { canonical: "react native", aliases: [], category: "technical" },
  { canonical: "flutter", aliases: [], category: "technical" },
  { canonical: "machine learning", aliases: ["ml"], category: "technical" },
  { canonical: "deep learning", aliases: [], category: "technical" },
  {
    canonical: "natural language processing",
    aliases: ["nlp"],
    category: "technical",
  },
  // tools / platforms / infra
  {
    canonical: "sql",
    aliases: ["postgres", "mysql", "sqlite"],
    category: "tool",
  },
  { canonical: "graphql", aliases: ["gql"], category: "tool" },
  { canonical: "aws", aliases: ["amazon web services"], category: "tool" },
  { canonical: "azure", aliases: ["microsoft azure"], category: "tool" },
  {
    canonical: "gcp",
    aliases: ["google cloud", "google cloud platform"],
    category: "tool",
  },
  { canonical: "docker", aliases: ["containers"], category: "tool" },
  { canonical: "kubernetes", aliases: ["k8s"], category: "tool" },
  { canonical: "terraform", aliases: [], category: "tool" },
  { canonical: "ansible", aliases: [], category: "tool" },
  { canonical: "jenkins", aliases: [], category: "tool" },
  { canonical: "git", aliases: ["github", "gitlab"], category: "tool" },
  { canonical: "jira", aliases: [], category: "tool" },
  { canonical: "confluence", aliases: [], category: "tool" },
  { canonical: "pytorch", aliases: ["torch"], category: "tool" },
  { canonical: "tensorflow", aliases: ["tf"], category: "tool" },
  { canonical: "scikit-learn", aliases: ["sklearn"], category: "tool" },
  { canonical: "pandas", aliases: [], category: "tool" },
  { canonical: "numpy", aliases: [], category: "tool" },
  { canonical: "fastapi", aliases: [], category: "tool" },
  { canonical: "flask", aliases: [], category: "tool" },
  { canonical: "django", aliases: [], category: "tool" },
  { canonical: "kafka", aliases: [], category: "tool" },
  { canonical: "redis", aliases: [], category: "tool" },
  { canonical: "elasticsearch", aliases: ["elastic"], category: "tool" },
  { canonical: "spark", aliases: ["apache spark"], category: "tool" },
  { canonical: "tableau", aliases: [], category: "tool" },
  { canonical: "power bi", aliases: ["powerbi"], category: "tool" },
  {
    canonical: "excel",
    aliases: ["microsoft excel", "ms excel"],
    category: "tool",
  },
  { canonical: "salesforce", aliases: [], category: "tool" },
  { canonical: "hubspot", aliases: [], category: "tool" },
  { canonical: "sap", aliases: [], category: "tool" },
  { canonical: "quickbooks", aliases: [], category: "tool" },
  { canonical: "workday", aliases: [], category: "tool" },
  { canonical: "zendesk", aliases: [], category: "tool" },
  { canonical: "servicenow", aliases: [], category: "tool" },
  { canonical: "figma", aliases: [], category: "tool" },
  { canonical: "photoshop", aliases: ["adobe photoshop"], category: "tool" },
  {
    canonical: "illustrator",
    aliases: ["adobe illustrator"],
    category: "tool",
  },
  { canonical: "autocad", aliases: [], category: "tool" },
  // engineering concepts
  { canonical: "accessibility", aliases: ["a11y"], category: "concept" },
  { canonical: "frontend", aliases: ["front-end"], category: "concept" },
  { canonical: "backend", aliases: ["back-end"], category: "concept" },
  { canonical: "security", aliases: ["cybersecurity"], category: "concept" },
  {
    canonical: "testing",
    aliases: ["unittest", "pytest"],
    category: "concept",
  },
  { canonical: "microservices", aliases: [], category: "concept" },
  { canonical: "agile", aliases: ["scrum"], category: "concept" },
  { canonical: "kanban", aliases: [], category: "concept" },
  { canonical: "blockchain", aliases: [], category: "concept" },
  { canonical: "devops", aliases: [], category: "concept" },
  {
    canonical: "ci/cd",
    aliases: ["continuous integration", "continuous deployment"],
    category: "concept",
  },
  {
    canonical: "rest api",
    aliases: ["restful api", "rest apis"],
    category: "concept",
  },
  { canonical: "design patterns", aliases: [], category: "concept" },
  { canonical: "data structures", aliases: [], category: "concept" },
  { canonical: "algorithms", aliases: [], category: "concept" },
  { canonical: "cloud computing", aliases: [], category: "concept" },
  { canonical: "system design", aliases: [], category: "concept" },
  {
    canonical: "tdd",
    aliases: ["test driven development", "test-driven development"],
    category: "concept",
  },
  { canonical: "ux design", aliases: ["user experience"], category: "concept" },
  {
    canonical: "ui design",
    aliases: ["user interface design"],
    category: "concept",
  },
  { canonical: "project management", aliases: [], category: "concept" },
  { canonical: "change management", aliases: [], category: "concept" },
  { canonical: "risk management", aliases: [], category: "concept" },
  { canonical: "quality assurance", aliases: ["qa"], category: "concept" },
  // product / data domain
  { canonical: "roadmap", aliases: [], category: "domain" },
  { canonical: "stakeholder management", aliases: [], category: "domain" },
  { canonical: "prioritization", aliases: [], category: "domain" },
  { canonical: "a/b testing", aliases: ["ab testing"], category: "domain" },
  { canonical: "analytics", aliases: [], category: "domain" },
  { canonical: "statistics", aliases: ["stats"], category: "domain" },
  { canonical: "data visualization", aliases: [], category: "domain" },
  // finance / accounting domain
  { canonical: "financial analysis", aliases: [], category: "domain" },
  { canonical: "budgeting", aliases: [], category: "domain" },
  { canonical: "forecasting", aliases: [], category: "domain" },
  { canonical: "bookkeeping", aliases: [], category: "domain" },
  { canonical: "accounts payable", aliases: ["ap"], category: "domain" },
  { canonical: "accounts receivable", aliases: ["ar"], category: "domain" },
  { canonical: "payroll", aliases: [], category: "domain" },
  { canonical: "auditing", aliases: ["audit"], category: "domain" },
  { canonical: "tax preparation", aliases: [], category: "domain" },
  { canonical: "gaap", aliases: [], category: "domain" },
  // sales / account management domain
  { canonical: "lead generation", aliases: [], category: "domain" },
  { canonical: "account management", aliases: [], category: "domain" },
  {
    canonical: "crm",
    aliases: ["customer relationship management"],
    category: "domain",
  },
  { canonical: "sales pipeline", aliases: [], category: "domain" },
  { canonical: "cold calling", aliases: [], category: "domain" },
  { canonical: "upselling", aliases: ["cross-selling"], category: "domain" },
  { canonical: "customer retention", aliases: [], category: "domain" },
  // human resources domain
  {
    canonical: "recruiting",
    aliases: ["talent acquisition"],
    category: "domain",
  },
  { canonical: "onboarding", aliases: [], category: "domain" },
  { canonical: "employee relations", aliases: [], category: "domain" },
  { canonical: "benefits administration", aliases: [], category: "domain" },
  { canonical: "performance management", aliases: [], category: "domain" },
  // healthcare domain
  { canonical: "patient care", aliases: [], category: "domain" },
  { canonical: "clinical documentation", aliases: [], category: "domain" },
  { canonical: "hipaa", aliases: [], category: "domain" },
  {
    canonical: "electronic health records",
    aliases: ["ehr", "emr"],
    category: "domain",
  },
  { canonical: "medical billing", aliases: [], category: "domain" },
  // legal domain
  { canonical: "contract review", aliases: [], category: "domain" },
  { canonical: "legal research", aliases: [], category: "domain" },
  { canonical: "litigation", aliases: [], category: "domain" },
  {
    canonical: "regulatory compliance",
    aliases: ["compliance"],
    category: "domain",
  },
  { canonical: "due diligence", aliases: [], category: "domain" },
  // education domain
  { canonical: "curriculum development", aliases: [], category: "domain" },
  { canonical: "lesson planning", aliases: [], category: "domain" },
  { canonical: "classroom management", aliases: [], category: "domain" },
  { canonical: "instructional design", aliases: [], category: "domain" },
  // operations / supply chain domain
  {
    canonical: "supply chain management",
    aliases: ["supply chain"],
    category: "domain",
  },
  { canonical: "inventory management", aliases: [], category: "domain" },
  { canonical: "procurement", aliases: [], category: "domain" },
  { canonical: "vendor management", aliases: [], category: "domain" },
  { canonical: "logistics", aliases: [], category: "domain" },
  // customer service domain
  {
    canonical: "customer support",
    aliases: ["customer service"],
    category: "domain",
  },
  { canonical: "technical support", aliases: [], category: "domain" },
  { canonical: "conflict resolution", aliases: [], category: "domain" },
  // soft skills
  { canonical: "communication", aliases: [], category: "soft" },
  { canonical: "leadership", aliases: [], category: "soft" },
  { canonical: "teamwork", aliases: ["collaboration"], category: "soft" },
  {
    canonical: "problem solving",
    aliases: ["problem-solving"],
    category: "soft",
  },
  { canonical: "adaptability", aliases: ["flexibility"], category: "soft" },
  { canonical: "time management", aliases: [], category: "soft" },
  { canonical: "critical thinking", aliases: [], category: "soft" },
  { canonical: "creativity", aliases: [], category: "soft" },
  { canonical: "attention to detail", aliases: [], category: "soft" },
  {
    canonical: "decision making",
    aliases: ["decision-making"],
    category: "soft",
  },
  { canonical: "emotional intelligence", aliases: [], category: "soft" },
  { canonical: "negotiation", aliases: [], category: "soft" },
  {
    canonical: "organization",
    aliases: ["organizational skills"],
    category: "soft",
  },
  {
    canonical: "public speaking",
    aliases: ["presentation skills"],
    category: "soft",
  },
  { canonical: "mentoring", aliases: ["coaching"], category: "soft" },
  { canonical: "interpersonal skills", aliases: [], category: "soft" },
  { canonical: "work ethic", aliases: [], category: "soft" },
  // marketing
  {
    canonical: "seo",
    aliases: ["search engine optimization"],
    category: "marketing",
  },
  { canonical: "branding", aliases: ["brand strategy"], category: "marketing" },
  { canonical: "campaign management", aliases: [], category: "marketing" },
  { canonical: "content marketing", aliases: [], category: "marketing" },
  {
    canonical: "social media marketing",
    aliases: ["social media"],
    category: "marketing",
  },
  { canonical: "email marketing", aliases: [], category: "marketing" },
  { canonical: "digital marketing", aliases: [], category: "marketing" },
  { canonical: "copywriting", aliases: [], category: "marketing" },
  { canonical: "market research", aliases: [], category: "marketing" },
  {
    canonical: "ppc",
    aliases: ["pay-per-click", "google ads"],
    category: "marketing",
  },
  {
    canonical: "conversion rate optimization",
    aliases: ["cro"],
    category: "marketing",
  },
  { canonical: "public relations", aliases: ["pr"], category: "marketing" },
];

export const defaultSkillAliases = deriveSkillAliases(defaultKeywordRegistry);

export const softwareEngineerProfile: ATSProfile = {
  name: "software-engineer",
  mandatorySkills: ["javascript", "typescript", "react", "node"],
  optionalSkills: ["graphql", "sql", "docker"],
  minExperience: 3,
};

export const dataScientistProfile: ATSProfile = {
  name: "data-scientist",
  mandatorySkills: ["python", "sql", "statistics"],
  optionalSkills: ["pandas", "numpy", "pytorch", "tensorflow"],
  minExperience: 2,
};

export const productManagerProfile: ATSProfile = {
  name: "product-manager",
  mandatorySkills: ["roadmap", "stakeholder management", "prioritization"],
  optionalSkills: ["a/b testing", "analytics", "sql"],
  minExperience: 3,
};

export const defaultProfiles: ATSProfile[] = [
  softwareEngineerProfile,
  dataScientistProfile,
  productManagerProfile,
];
